language: node_js
node_js:
  - '10.16.3'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test
  - yarn build:beta
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn publish:chrome; fi'
